const translations = {
  en: {
    nav_home: "Home",
    nav_features: "Features",
    nav_hardware: "Hardware",
    nav_download: "Download",
    nav_contact: "Contact",
    nav_get_started: "Get Started",
    hero_subtitle: "Next-Gen Early Warning",
    hero_title: "Seismo Guard",
    hero_description: "Advanced real-time earthquake detection and alert system powered by IoT technology. Protect what matters most with split-second precision.",
    hero_download: "Download APK",
    hero_github: "View on GitHub",
    trust_realtime_title: "Real-time Alerts",
    trust_realtime_desc: "Instant notifications delivered within milliseconds of detection.",
    trust_reliable_title: "Reliable Monitoring",
    trust_reliable_desc: "24/7 continuous sensor scanning with zero downtime architecture.",
    trust_multiplatform_title: "Multi-platform",
    trust_multiplatform_desc: "Access your dashboard on Android, iOS, Windows, macOS, and Linux.",
    trust_emergency_title: "Emergency Ready",
    trust_emergency_desc: "Built-in emergency protocols and local safety guidelines.",
    features_header_title: "Precision in Every Second",
    features_header_desc: "Seismo Guard combines high-sensitivity IoT sensors with cloud intelligence to provide the most reliable earthquake alert system.",
    feat_smart_title: "Smart Notifications",
    feat_smart_desc: "Context-aware alerts that adapt to your location and the intensity of the seismic activity.",
    feat_emergency_title: "Emergency Mode",
    feat_emergency_desc: "Automatic activation of home safety systems and guidance for immediate protection.",
    feat_offline_title: "Offline Capability",
    feat_offline_desc: "Critical alert protocols function even when primary internet connectivity is compromised.",
    feat_multi_title: "Multi-language",
    feat_multi_desc: "Available in over 15 languages to serve diverse global communities effectively.",
    hardware_title: "Powered by IoT Hardware",
    hardware_desc: "Our proprietary sensor modules use high-precision MEMS accelerometers to detect even the slightest P-wave vibrations before the destructive S-waves arrive.",
    hardware_item1: "Sub-millisecond latency",
    hardware_item2: "Low power consumption (battery backed)",
    hardware_item3: "Industrial-grade seismic sensors",
    screenshots_title: "Intuitive Interface",
    screenshots_desc: "Monitor seismic activity and manage your alerts through our clean, modern application dashboard.",
    download_title: "Download Seismo Guard",
    download_desc: "Available on all major platforms. Protect your home and family today.",
    download_android_desc: "v2.4.0 (Latest)",
    download_ios_title: "iOS",
    download_ios_desc: "Coming Soon",
    download_windows_desc: "v2.3.1",
    download_linux_desc: "v2.3.1",
    contact_title: "Get in Touch",
    contact_desc: "Need support or interested in a partnership? Our team is here to help you 24/7.",
    cta_title: "Ready to Stay Guarded?",
    cta_desc: "Join thousands of users who trust Seismo Guard for earthquake safety.",
    cta_btn: "Download Now",
    footer_brand_desc: "The world's most accessible early warning system for seismic activity. Built with passion for human safety.",
    footer_product: "Product",
    footer_company: "Company",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",
    footer_copyright: "© 2026 Seismo Guard IoT System. All rights reserved."
  },
  id: {
    nav_home: "Beranda",
    nav_features: "Fitur",
    nav_hardware: "Perangkat Keras",
    nav_download: "Unduh",
    nav_contact: "Kontak",
    nav_get_started: "Mulai Sekarang",
    hero_subtitle: "Peringatan Dini Generasi Terbaru",
    hero_title: "Seismo Guard",
    hero_description: "Sistem deteksi dan peringatan gempa bumi real-time canggih yang didukung oleh teknologi IoT. Lindungi yang paling berharga dengan presisi sepersekian detik.",
    hero_download: "Unduh APK",
    hero_github: "Lihat di GitHub",
    trust_realtime_title: "Peringatan Real-time",
    trust_realtime_desc: "Notifikasi instan dikirimkan dalam milidetik setelah deteksi.",
    trust_reliable_title: "Pemantauan Andal",
    trust_reliable_desc: "Pemindaian sensor berkelanjutan 24/7 dengan arsitektur tanpa downtime.",
    trust_multiplatform_title: "Multi-platform",
    trust_multiplatform_desc: "Akses dasbor Anda di Android, iOS, Windows, macOS, dan Linux.",
    trust_emergency_title: "Siap Darurat",
    trust_emergency_desc: "Protokol darurat bawaan dan panduan keselamatan lokal.",
    features_header_title: "Presisi di Setiap Detik",
    features_header_desc: "Seismo Guard menggabungkan sensor IoT sensitivitas tinggi dengan kecerdasan cloud untuk menyediakan sistem peringatan gempa bumi yang paling andal.",
    feat_smart_title: "Notifikasi Pintar",
    feat_smart_desc: "Peringatan sadar konteks yang beradaptasi dengan lokasi Anda dan intensitas aktivitas seismik.",
    feat_emergency_title: "Mode Darurat",
    feat_emergency_desc: "Aktivasi otomatis sistem keamanan rumah dan panduan untuk perlindungan segera.",
    feat_offline_title: "Kemampuan Offline",
    feat_offline_desc: "Protokol peringatan kritis berfungsi bahkan ketika konektivitas internet utama terganggu.",
    feat_multi_title: "Multi-bahasa",
    feat_multi_desc: "Tersedia dalam lebih dari 15 bahasa untuk melayani komunitas global yang beragam secara efektif.",
    hardware_title: "Didukung oleh Perangkat Keras IoT",
    hardware_desc: "Modul sensor eksklusif kami menggunakan akselerometer MEMS presisi tinggi untuk mendeteksi getaran gelombang-P sekecil apa pun sebelum gelombang-S yang merusak tiba.",
    hardware_item1: "Latensi sub-milidetik",
    hardware_item2: "Konsumsi daya rendah (didukung baterai)",
    hardware_item3: "Sensor seismik tingkat industri",
    screenshots_title: "Antarmuka Intuitif",
    screenshots_desc: "Pantau aktivitas seismik dan kelola peringatan Anda melalui dasbor aplikasi modern kami yang bersih.",
    download_title: "Unduh Seismo Guard",
    download_desc: "Tersedia di semua platform utama. Lindungi rumah dan keluarga Anda hari ini.",
    download_android_desc: "v2.4.0 (Terbaru)",
    download_ios_title: "iOS",
    download_ios_desc: "Segera Hadir",
    download_windows_desc: "v2.3.1",
    download_linux_desc: "v2.3.1",
    contact_title: "Hubungi Kami",
    contact_desc: "Butuh dukungan atau tertarik dalam kemitraan? Tim kami ada di sini untuk membantu Anda 24/7.",
    cta_title: "Siap untuk Tetap Terlindungi?",
    cta_desc: "Bergabunglah dengan ribuan pengguna yang mempercayai Seismo Guard untuk keselamatan gempa bumi.",
    cta_btn: "Unduh Sekarang",
    footer_brand_desc: "Sistem peringatan dini aktivitas seismik paling mudah diakses di dunia. Dibangun dengan gairah untuk keselamatan manusia.",
    footer_product: "Produk",
    footer_company: "Perusahaan",
    footer_privacy: "Kebijakan Privasi",
    footer_terms: "Ketentuan Layanan",
    footer_copyright: "© 2026 Seismo Guard IoT System. Hak cipta dilindungi undang-undang."
  }
};
